# Generated by Django 2.2.6 on 2019-11-13 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0002_announcement_many_to_many_and_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'date_sent',
            },
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ManyToManyField(related_name='announcements',
                                         through='announcement.AnnouncementUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementuser',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='announcement_user', to='announcement.Announcement'),
        ),
        migrations.AddField(
            model_name='announcementuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='announcement_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='announcementuser',
            unique_together={('announcement', 'user')},
        ),
    ]
