# Generated by Django 2.2.6 on 2019-12-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_user_pivot_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='announcementuser',
            unique_together=set(),
        ),
    ]
