# Generated by Django 2.2.6 on 2019-11-13 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('is_registration_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('preevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='preevent.Preevent')),
            ],
            options={
                'ordering': ['preevent', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'task categories',
            },
        ),
        migrations.CreateModel(
            name='TaskWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('widget_parameters', jsonfield.fields.JSONField(null=True)),
                ('requires_validation', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='preevent.TaskCategory')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='preevent.Stage')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='preevent.TaskWidget')),
            ],
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_participating', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_registrants', to='preevent.Stage')),
                ('preevent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrants', to='preevent.Preevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preevent_registrants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('awaiting_validation', 'Awaiting validation'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('last_submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_responses', to='preevent.Registrant')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_responses', to='preevent.Task')),
            ],
            options={
                'get_latest_by': 'created_at',
                'unique_together': {('task', 'registrant')},
            },
        ),
    ]
