# Generated by Django 2.2.13 on 2020-12-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preevent', '0002_preevent_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='preevent',
            name='education_level',
            field=models.CharField(choices=[('SMA', 'SMA'), ('Kuliah', 'Kuliah'), ('SMA/Kuliah', 'SMA/Kuliah')], default=None, max_length=30, null=True),
        ),
    ]
