# Generated by Django 2.2.6 on 2019-10-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkavauth', '0002_add_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
