# Generated by Django 2.2.6 on 2019-11-11 07:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('arkavauth', '0003_prolong_user_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_education',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
