# Generated by Django 2.2.8 on 2020-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkavauth', '0004_prolong_user_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_education',
            field=models.CharField(choices=[('SMA', 'SMA'), ('Kuliah', 'Kuliah')],
                                   default=None, max_length=30, null=True),
        ),
    ]
