# Generated by Django 2.2.5 on 2019-10-15 13:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email_last_sent_at',
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('date_sent', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='announcements', 
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
