# Generated by Django 2.2.6 on 2019-10-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email_last_sent_at',
        ),
    ]
