# Generated by Django 2.2.6 on 2019-10-25 13:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresponse',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
