# Generated by Django 2.2.6 on 2019-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_taskresponse_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='institution',
            field=models.CharField(max_length=100),
        ),
    ]
