# Generated by Django 2.2.6 on 2019-10-29 13:50

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_taskresponse_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='widget_parameters_json',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
