# Generated by Django 2.2.6 on 2019-10-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_task_widget_parameters_json'),
        ('competition', '0004_prolong_team_institution'),
    ]

    operations = [
    ]
