# Generated by Django 2.2.6 on 2019-10-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_merge_migrations'),
        ('competition', '0005_task_is_user_task'),
    ]

    operations = [
    ]
