# Generated by Django 2.2.6 on 2019-10-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_transfer_widget_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='widget_parameters',
        ),
    ]
