# Generated by Django 2.2.6 on 2019-10-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_remove_task_widget_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='widget_parameters_json',
            new_name='widget_parameters',
        ),
    ]
