# Generated by Django 2.2.8 on 2020-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_usertaskresponse_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='education_level',
            field=models.CharField(choices=[('SMA', 'SMA'), ('Kuliah', 'Kuliah')],
                                   default=None, max_length=30, null=True),
        ),
    ]
