# Generated by Django 2.2.8 on 2020-11-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_competition_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='education_level',
            field=models.CharField(choices=[('SMA', 'SMA'), ('Kuliah', 'Kuliah'), ('SMA/Kuliah', 'SMA/Kuliah')],
                                   default=None, max_length=30, null=True),
        ),
    ]
