# Generated by Django 2.2.13 on 2021-02-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkalogica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='session',
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='submission',
                to='arkalogica.Session'),
        ),
    ]
