# Generated by Django 2.2.13 on 2021-01-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkalogica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='arkalogica.Session'),
            preserve_default=False,
        ),
    ]
