# Generated by Django 2.2.13 on 2021-02-01 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkalogica', '0002_submission_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='session',
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE,
                related_name='submission', to='arkalogica.Session'),
        ),
    ]
