# Generated by Django 2.2.13 on 2021-01-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkalogica', '0002_submission_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='session',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='submission',
                to='arkalogica.Session'
            ),
        ),
    ]
