# Generated by Django 2.2.8 on 2020-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcheckin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinattendance',
            name='last_sent_token',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
