# Generated by Django 2.2.8 on 2020-01-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcheckin', '0002_checkinattendance_last_sent_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinattendance',
            options={},
        ),
        migrations.RemoveField(
            model_name='checkinattendance',
            name='checkin_time',
        ),
        migrations.AddField(
            model_name='checkinattendance',
            name='pax',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='checkinattendance',
            name='pax_checked_in',
            field=models.IntegerField(default=0),
        ),
    ]
