# Generated by Django 2.2.8 on 2020-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcheckin', '0003_use_pax_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinevent',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
