# Generated by Django 2.2.8 on 2020-02-02 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eventcheckin', '0004_checkinevent_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinattendance',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
