# Generated by Django 2.2.8 on 2020-02-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcheckin', '0005_checkinattendance_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinevent',
            name='begin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='checkinevent',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='checkinevent',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkinevent',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
