# Generated by Django 2.2.6 on 2019-11-23 22:35

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('is_registration_open', models.BooleanField(default=True)),
                ('short_desc', models.TextField(blank=True)),
                ('long_desc', models.TextField(blank=True)),
                ('begin_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MaineventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('mainevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages',
                                                to='mainevent.Mainevent')),
            ],
            options={
                'ordering': ['mainevent', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'task categories',
            },
        ),
        migrations.CreateModel(
            name='TaskWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('widget_parameters', jsonfield.fields.JSONField(null=True)),
                ('requires_validation', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks',
                                               to='mainevent.TaskCategory')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks',
                                            to='mainevent.Stage')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks',
                                             to='mainevent.TaskWidget')),
            ],
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_participating', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                   related_name='active_registrants', to='mainevent.Stage')),
                ('mainevent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                related_name='registrants', to='mainevent.Mainevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                           related_name='mainevent_registrants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
                'unique_together': {('mainevent', 'user')},
            },
        ),
        migrations.AddField(
            model_name='mainevent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mainevents',
                                    to='mainevent.MaineventCategory'),
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('awaiting_validation', 'Awaiting validation'),
                                                     ('completed', 'Completed'), ('rejected', 'Rejected')],
                                            max_length=20)),
                ('last_submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='task_responses', to='mainevent.Registrant')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_responses',
                                           to='mainevent.Task')),
            ],
            options={
                'get_latest_by': 'created_at',
                'unique_together': {('task', 'registrant')},
            },
        ),
    ]
