# Generated by Django 2.2.6 on 2019-11-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maineventcategory',
            options={'verbose_name_plural': 'mainevent categories'},
        ),
    ]
