# Generated by Django 2.2.8 on 2020-01-28 10:01

from django.db import migrations, models


def set_registrants_participating_false_forward(apps, schema_editor):
    Registrant = apps.get_model('mainevent', 'Registrant')
    for registrant in Registrant.objects.all():
        registrant.is_participating = False
        registrant.save()


def set_registrants_participating_false_reverse(apps, schema_editor):
    Registrant = apps.get_model('mainevent', 'Registrant')
    for registrant in Registrant.objects.all():
        registrant.is_participating = True
        registrant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mainevent', '0002_mainevent_categories_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainevent',
            name='seats_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainevent',
            name='seats_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_registrants_participating_false_forward, set_registrants_participating_false_reverse),
        migrations.AlterField(
            model_name='registrant',
            name='is_participating',
            field=models.BooleanField(default=False),
        ),
    ]
