# Generated by Django 2.2.13 on 2020-12-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainevent', '0003_add_seat_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainevent',
            name='education_level',
            field=models.CharField(choices=[('SMA', 'SMA'), ('Kuliah', 'Kuliah'), ('SMA/Kuliah', 'SMA/Kuliah')], default=None, max_length=30, null=True),
        ),
    ]
