# Generated by Django 2.2.6 on 2019-10-14 17:59

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to='')),
                ('original_filename', models.CharField(max_length=200)),
                ('file_size', models.BigIntegerField(null=True)),
                ('description', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
