name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
    - name: Run deployment script over SSH
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      with:
        args: "/root/deployment-scripts/deploy-production.sh"
